---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  annotations:
    controller-gen.kubebuilder.io/version: v0.12.1
  name: antstorvolumegroups.volume.antstor.alipay.com
spec:
  group: volume.antstor.alipay.com
  names:
    kind: AntstorVolumeGroup
    listKind: AntstorVolumeGroupList
    plural: antstorvolumegroups
    singular: antstorvolumegroup
  scope: Namespaced
  versions:
  - additionalPrinterColumns:
    - jsonPath: .spec.desiredVolumeSpec.sizeSymmetry
      name: symmetry
      type: string
    - jsonPath: .spec.totalSize
      name: size
      type: integer
    - jsonPath: .status.status
      name: status
      type: string
    - jsonPath: .metadata.creationTimestamp
      name: age
      type: date
    name: v1
    schema:
      openAPIV3Schema:
        description: AntstorVolumeGroup is the Schema for the AntstorVolumeGroup API
        properties:
          apiVersion:
            description: 'APIVersion defines the versioned schema of this representation
              of an object. Servers should convert recognized schemas to the latest
              internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
            type: string
          kind:
            description: 'Kind is a string value representing the REST resource this
              object represents. Servers may infer this from the endpoint the client
              submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
            type: string
          metadata:
            type: object
          spec:
            description: AntstorVolumeGroupSpec defines the desired state of AntstorVolumeGroup
            properties:
              desiredVolumeSpec:
                description: DesiredVolumeSpec contains specifications of volumes
                properties:
                  annotations:
                    additionalProperties:
                      type: string
                    description: Annotatioins for volumes
                    type: object
                  countRange:
                    properties:
                      max:
                        type: integer
                      min:
                        type: integer
                    type: object
                  desiredCount:
                    type: integer
                  labels:
                    additionalProperties:
                      type: string
                    description: Labels for volumes
                    type: object
                  sizeRange:
                    properties:
                      max:
                        anyOf:
                        - type: integer
                        - type: string
                        pattern: ^(\+|-)?(([0-9]+(\.[0-9]*)?)|(\.[0-9]+))(([KMGTPE]i)|[numkMGTPE]|([eE](\+|-)?(([0-9]+(\.[0-9]*)?)|(\.[0-9]+))))?$
                        x-kubernetes-int-or-string: true
                      min:
                        anyOf:
                        - type: integer
                        - type: string
                        pattern: ^(\+|-)?(([0-9]+(\.[0-9]*)?)|(\.[0-9]+))(([KMGTPE]i)|[numkMGTPE]|([eE](\+|-)?(([0-9]+(\.[0-9]*)?)|(\.[0-9]+))))?$
                        x-kubernetes-int-or-string: true
                    type: object
                  sizeSymmetry:
                    type: string
                required:
                - sizeSymmetry
                type: object
              stragety:
                description: Stragety of scheduling volumes
                properties:
                  allowEmptyNode:
                    type: boolean
                  emptyThreasholdPct:
                    description: EmptyThreashold defines the usage percentage of storagepool
                      being considered empty.
                    type: integer
                  name:
                    type: string
                type: object
              totalSize:
                description: TotalSize in bytes
                format: int64
                type: integer
              uuid:
                description: ID is uuid generated by controller for each volume
                type: string
              volumes:
                description: Volumes in the VolumeGroup
                items:
                  properties:
                    size:
                      format: int64
                      type: integer
                    targetNodeName:
                      type: string
                    volId:
                      properties:
                        name:
                          type: string
                        namespace:
                          type: string
                        uuid:
                          type: string
                      required:
                      - name
                      - namespace
                      - uuid
                      type: object
                  required:
                  - size
                  - targetNodeName
                  - volId
                  type: object
                type: array
            required:
            - totalSize
            type: object
          status:
            description: AntstorVolumeGroupStatus defines the observed state of AntstorVolumeGroup
            properties:
              message:
                type: string
              status:
                default: creating
                enum:
                - creating
                - ready
                - deleted
                type: string
              volumeStatus:
                items:
                  properties:
                    message:
                      description: message of volume
                      type: string
                    spdkTarget:
                      properties:
                        addrFam:
                          type: string
                        address:
                          type: string
                        bdevName:
                          type: string
                        nsUuid:
                          type: string
                        sn:
                          type: string
                        subsysNqn:
                          type: string
                        svcID:
                          type: string
                        transType:
                          type: string
                      required:
                      - addrFam
                      - address
                      - bdevName
                      - nsUuid
                      - sn
                      - subsysNqn
                      - svcID
                      - transType
                      type: object
                    status:
                      default: creating
                      description: status of volume
                      enum:
                      - creating
                      - ready
                      - deleted
                      type: string
                    uuid:
                      description: UUID of volume
                      type: string
                  required:
                  - uuid
                  type: object
                type: array
            type: object
        type: object
    served: true
    storage: true
    subresources:
      status: {}
